version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - mongo
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/keola
      - SPRING_DATASOURCE_USERNAME=keola
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/keola
      - SPRING_R2DBC_USERNAME=keola
      - SPRING_R2DBC_PASSWORD=1234
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/ordermanagementsystem
    ports:
      - "8080:8080"

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: keola
      POSTGRES_USER: keola
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"


